name: AGLint
env:
  NODE_VERSION: 25

on:
  workflow_dispatch:
  #push:
    #branches:
      #- main
    #paths:
      #- "**/*.txt"
  #pull_request:
    #branches:
      #- main
    #paths:
      #- "**/*.txt"

jobs:
  lint:
    name: Run AGLint
    runs-on: ubuntu-latest
    steps:
      - name: Check out to repository
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: AGLint cache
        uses: actions/cache@v5
        with:
          path: .aglintcache
          key: >
            ${{ runner.os }}-aglint-${{ hashFiles(
              '**/.aglintignore',
              '**/.aglintrc',
              '**/.aglintrc.json',
              '**/.aglintrc.yaml',
              '**/.aglintrc.yml',
              '**/aglint.config.json',
              '**/aglint.config.yaml',
              '**/aglint.config.yml',
              '**/package.json',
              'package-lock.json'
            ) }}
          restore-keys: |
            ${{ runner.os }}-aglint-
      # If the linter found any errors, it will exit with a non-zero code, which will cause the job to fail
      - name: Run AGLint
        run: npm run aglint
