name: 🔄 Update External Lists
on:
  #schedule: [{cron: "0 23 * * 0"}] # Once a week at midnight UTC+1
  workflow_dispatch:
    inputs:
      force_update:
        description: "Force update all lists"
        type: boolean
        default: false
permissions:
  contents: write
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true
env:
  DEBIAN_FRONTEND: noninteractive
  PYTHONOPTIMIZE: 2
  PYTHONNODEBUGRANGES: 1
  PYTHONDONTWRITEBYTECODE: 1
  PYTHONUTF8: 1
  PYTHONSAFEPATH: 1
  PYTHON_COLORS: 0
  LC_ALL: C
  GITHUB_TOKEN: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
jobs:
  update-external:
    name: Download External Lists
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"
      - uses: astral-sh/setup-uv@v9.0.0
        with:
          version: "latest"
          enable-cache: true
          github-token: ${{ github.token || secrets.PAT }}
      - run: uv sync
      - name: Run update script
        id: update
        run: |
          set -e
          uv run python3 -OO -m Scripts.update_lists --output-dir lists/external --max-concurrent 8 --dedupe
      - name: Run dead domains linter
        if: success()
        continue-on-error: true
        run: |
          if command -v bunx &>/dev/null; then
            bunx dead-domains-linter -i "lists/external/*.txt" || :
          elif command -v npx &>/dev/null; then
            npx dead-domains-linter -i "lists/external/*.txt" || :
          fi
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: update external filter lists"
          file_pattern: "lists/external/**/*.txt lists/sources-metadata.json"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
